#numpy

In [1]:
import numpy as np

In [2]:
myarr = np.array([[2,3,45,]],np.int8)

In [3]:
print(myarr)

[[ 2  3 45]]


In [4]:
myarr[0]

array([ 2,  3, 45], dtype=int8)

In [5]:
myarr[0,0]

np.int8(2)

In [6]:
nnn = np.array([[1,3,4],[2,42,5]])

In [7]:
nnn.shape

(2, 3)

In [8]:
nnn[0][2]

np.int64(4)

In [7]:
myarr[0]


array([ 2,  3, 45], dtype=int8)

In [8]:
myarr[0]

array([ 2,  3, 45], dtype=int8)

In [9]:
myarr.shape

(1, 3)

In [10]:
myarr.dtype

dtype('int8')

In [11]:
myarr.size


3

In [12]:
zeros = np.zeros((2,3))

In [13]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [14]:
mynums = np.arange(15)

In [15]:
mynums

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [16]:
lnums = np.linspace(1,5,10)

In [17]:
lnums

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [18]:
np.linspace(1,50,5)

array([ 1.  , 13.25, 25.5 , 37.75, 50.  ])

In [19]:
np.linspace(1,50,10)

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [20]:
np.linspace(0,50,5)

array([ 0. , 12.5, 25. , 37.5, 50. ])

In [21]:
np.linspace(10,50,5)

array([10., 20., 30., 40., 50.])

In [22]:
np.linspace(0,50,10)

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [23]:
np.linspace(0,50,11,dtype= np.int32)

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50], dtype=int32)

In [24]:
np.identity(40,dtype=np.int32)

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 1, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 1, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 0, ..., 0, 0, 1]], dtype=int32)

In [25]:
np.empty(10)

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [26]:
np.empty_like(10)

array(0)

In [27]:
np.empty_like([2,4,3])

array([0, 0, 0])

In [28]:
np.empty_like(lnums)

array([ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222,
       27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ])

In [29]:
np.empty_like(lnums).size

10

In [30]:
lnums.shape

(10,)

In [31]:
lnums.data

In [32]:
lnums.dtype

dtype('float64')

In [33]:
lnums.astype(np.int32)

array([1, 1, 1, 2, 2, 3, 3, 4, 4, 5], dtype=int32)

In [34]:
np.empty_like(lnums).reshape(2,5)

array([[ 0.        ,  5.55555556, 11.11111111, 16.66666667, 22.22222222],
       [27.77777778, 33.33333333, 38.88888889, 44.44444444, 50.        ]])

In [35]:
lnums

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [36]:
lnums.reshape(2,5)

array([[1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778],
       [3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]])

In [37]:
lnums

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [38]:
lnums = lnums.reshape(2,5)

In [39]:
lnums

array([[1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778],
       [3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]])

In [40]:
lnums.ravel()

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [41]:
lnums

array([[1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778],
       [3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]])

In [42]:
lnums = lnums.ravel()

In [43]:
lnums

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [44]:
lnums.shape

(10,)

In [45]:
lnums.size

10

In [46]:
lnums.reshape(2,5)

array([[1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778],
       [3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ]])

In [47]:
lnums = lnums.reshape(2,5)

In [48]:
flat_lnums = lnums.reshape(-1)

In [49]:
flat_lnums

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [50]:
flat_lnums.shape

(10,)

In [51]:
lnums.shape

(2, 5)

In [52]:
new_arr = np.array([[2,3,4],
                    [5,3,6],
                    [9,0,9]])

In [53]:
new_arr

array([[2, 3, 4],
       [5, 3, 6],
       [9, 0, 9]])

In [54]:
new_arr.sum(axis =1)

array([ 9, 14, 18])

In [55]:
new_arr.sum(axis = 0)

array([16,  6, 19])

In [56]:
new_arr.sum()

np.int64(41)

In [57]:
for i in new_arr:
    print(i)

[2 3 4]
[5 3 6]
[9 0 9]


In [58]:
for i in new_arr.ravel():
    print(i)

2
3
4
5
3
6
9
0
9


In [59]:
for i in new_arr.flat:
    print(i)

2
3
4
5
3
6
9
0
9


In [60]:
new_arr

array([[2, 3, 4],
       [5, 3, 6],
       [9, 0, 9]])

In [61]:
new_arr.flat

In [62]:
new_arr.dtype

dtype('int64')

In [63]:
new_arr.ndim

2

In [64]:
new_arr.size

9

In [65]:
new_arr.itemsize

8

In [66]:
new_arr.nbytes

72

In [67]:
new_arr.argmax()

np.int64(6)

In [68]:
new_arr.argmin()

np.int64(7)

In [69]:
new_arr

array([[2, 3, 4],
       [5, 3, 6],
       [9, 0, 9]])

In [70]:
np.__version__

'2.1.1'

In [71]:
new_arr.argsort(axis = None)

array([7, 0, 4, 1, 2, 3, 5, 6, 8])

In [72]:
new_arr.argsort()

array([[0, 1, 2],
       [1, 0, 2],
       [1, 0, 2]])

In [73]:
new_arr.argsort(axis=1)

array([[0, 1, 2],
       [1, 0, 2],
       [1, 0, 2]])

In [74]:
new_arr.argsort(axis =0)

array([[0, 2, 0],
       [1, 0, 1],
       [2, 1, 2]])

In [75]:
na = np.array([3,5,2,5])

In [76]:
na

array([3, 5, 2, 5])

In [77]:
na.argsort(axis = 0)

array([2, 0, 1, 3])

In [78]:
new_arr

array([[2, 3, 4],
       [5, 3, 6],
       [9, 0, 9]])

In [79]:
new_arr.ndim

2

In [80]:
new_arr.nbytes

72

In [81]:
new_arr.argsort()

array([[0, 1, 2],
       [1, 0, 2],
       [1, 0, 2]])

In [82]:
new_zeros = np.zeros([2,4])

In [83]:
new_zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [84]:
new_arr.argmax()

np.int64(6)

In [85]:
kmv_arr = np.array([[23,22,21],[44,55,66]])

In [86]:
kmv_arr

array([[23, 22, 21],
       [44, 55, 66]])

In [87]:
kmv_arr.argsort()

array([[2, 1, 0],
       [0, 1, 2]])

In [88]:
kmv_arr.argmin()

np.int64(2)

In [89]:
kmv_arr.argmin(axis=0)

array([0, 0, 0])

In [90]:
kmv_arr.argmin(axis=1)

array([2, 0])

In [91]:
kmv_arr.argmax()


np.int64(5)

In [92]:
kmv_arr.argmax(axis=1)

array([0, 2])

In [93]:
kmv_arr.sum()

np.int64(231)

In [94]:
kmv_arr.sum(axis=1)

array([ 66, 165])

In [95]:
kmv_arr.sum(axis =0)

array([67, 77, 87])

In [96]:
kmv_arr.sum(0)

array([67, 77, 87])

In [97]:
kmv_arr2 = np.array([[2,2,2],
                    [1,2,1]])

In [98]:
kmv_arr

array([[23, 22, 21],
       [44, 55, 66]])

In [99]:
kmv_arr2

array([[2, 2, 2],
       [1, 2, 1]])

In [100]:
kmv_arr + kmv_arr2

array([[25, 24, 23],
       [45, 57, 67]])

In [101]:
kmv_arr == kmv_arr2

array([[False, False, False],
       [False, False, False]])

In [102]:
kmv_arr.reshape(3,2)

array([[23, 22],
       [21, 44],
       [55, 66]])

In [103]:
kmv_arr = kmv_arr.reshape(3,2)

In [104]:
kmv_arr.ravel()

array([23, 22, 21, 44, 55, 66])

In [105]:
kmv_arr

array([[23, 22],
       [21, 44],
       [55, 66]])

In [106]:
kmv_arr = kmv_arr.ravel()

In [107]:
kmv_arr

array([23, 22, 21, 44, 55, 66])

In [108]:
kmv_arr.reshape(2,3)

array([[23, 22, 21],
       [44, 55, 66]])

In [109]:
kmv_arr = kmv_arr.reshape(kmv_arr2.shape)

In [110]:
kmv_arr

array([[23, 22, 21],
       [44, 55, 66]])

In [111]:
kmv_arr2

array([[2, 2, 2],
       [1, 2, 1]])

In [112]:
kmv_arr*kmv_arr2

array([[ 46,  44,  42],
       [ 44, 110,  66]])

In [113]:
np.sqrt(kmv_arr)

array([[4.79583152, 4.69041576, 4.58257569],
       [6.63324958, 7.41619849, 8.1240384 ]])

In [114]:
kmv_arr.min()


np.int64(21)

In [115]:
kmv_arr.min(axis=1)

array([21, 44])

In [116]:
kmv_arr.min(axis = 0)

array([23, 22, 21])

In [117]:
kmv_arr.sort()

In [118]:
kmv_arr

array([[21, 22, 23],
       [44, 55, 66]])

In [119]:
kmv_arr.sort(axis= 0)

In [120]:
kmv_arr

array([[21, 22, 23],
       [44, 55, 66]])

In [121]:
kmv_arr.sort(axis=1)

In [122]:
kmv_arr

array([[21, 22, 23],
       [44, 55, 66]])

In [123]:
kmv_arr

array([[21, 22, 23],
       [44, 55, 66]])

In [124]:
np.where(kmv_arr<70)

(array([0, 0, 0, 1, 1, 1]), array([0, 1, 2, 0, 1, 2]))

In [125]:
kmv_arr

array([[21, 22, 23],
       [44, 55, 66]])

In [126]:
np.count_nonzero(kmv_arr)

6

In [127]:
np.nonzero(kmv_arr)

(array([0, 0, 0, 1, 1, 1]), array([0, 1, 2, 0, 1, 2]))

kmv_arr[1,2] ==0

In [128]:
kmv_arr

array([[21, 22, 23],
       [44, 55, 66]])

In [129]:
np.nonzero(kmv_arr)

(array([0, 0, 0, 1, 1, 1]), array([0, 1, 2, 0, 1, 2]))

In [130]:
import sys


In [131]:
py_ar = [2,3,5,6]

In [132]:
np_ar = np.array(py_ar)

In [133]:
np_ar

array([2, 3, 5, 6])

In [134]:
sys.getsizeof(py_ar)

88

In [135]:
sys.getsizeof(np_ar)

144

In [136]:
np_ar.nbytes

32

In [137]:
np_ar.itemsize

8

In [138]:
np_ar.itemsize * np_ar.size

32

In [139]:
kmv_arr.T

array([[21, 44],
       [22, 55],
       [23, 66]])

In [140]:
kmv_arr

array([[21, 22, 23],
       [44, 55, 66]])

In [141]:
kmv_arr.tolist()

[[21, 22, 23], [44, 55, 66]]

In [142]:
type(kmv_arr)

numpy.ndarray

In [143]:
type(kmv_arr.tolist())

list

In [144]:
ar2 = np.ones((2,6))
ar2

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [145]:
ar3 = np.arange(10,100,2)

In [146]:
ar3

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [147]:
ar3.dtype

dtype('int64')

In [148]:
ar4 = ar3.copy()
ar4

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [149]:
ar4[10] = 50
ar4

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 50, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [150]:
ar3

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [151]:
ar3[2] = 100
ar3


array([ 10,  12, 100,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98])

In [152]:
ar4

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 50, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76,
       78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [153]:
ar3.itemsize

8

In [154]:
ar3 = ar3.astype("float")

In [155]:
ar3.itemsize

8

In [156]:
ar3

array([ 10.,  12., 100.,  16.,  18.,  20.,  22.,  24.,  26.,  28.,  30.,
        32.,  34.,  36.,  38.,  40.,  42.,  44.,  46.,  48.,  50.,  52.,
        54.,  56.,  58.,  60.,  62.,  64.,  66.,  68.,  70.,  72.,  74.,
        76.,  78.,  80.,  82.,  84.,  86.,  88.,  90.,  92.,  94.,  96.,
        98.])

In [157]:
ar3.itemsize

8

In [158]:
ar3 = ar3.astype(np.int32)

In [159]:
ar3

array([ 10,  12, 100,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98], dtype=int32)

In [160]:
ar3.itemsize

4

In [161]:
ar3

array([ 10,  12, 100,  16,  18,  20,  22,  24,  26,  28,  30,  32,  34,
        36,  38,  40,  42,  44,  46,  48,  50,  52,  54,  56,  58,  60,
        62,  64,  66,  68,  70,  72,  74,  76,  78,  80,  82,  84,  86,
        88,  90,  92,  94,  96,  98], dtype=int32)

In [162]:
ar3=ar3.reshape(5,9)
ar3

array([[ 10,  12, 100,  16,  18,  20,  22,  24,  26],
       [ 28,  30,  32,  34,  36,  38,  40,  42,  44],
       [ 46,  48,  50,  52,  54,  56,  58,  60,  62],
       [ 64,  66,  68,  70,  72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90,  92,  94,  96,  98]], dtype=int32)

In [163]:
ar3[2]

array([46, 48, 50, 52, 54, 56, 58, 60, 62], dtype=int32)

In [164]:
ar3[2:]

array([[46, 48, 50, 52, 54, 56, 58, 60, 62],
       [64, 66, 68, 70, 72, 74, 76, 78, 80],
       [82, 84, 86, 88, 90, 92, 94, 96, 98]], dtype=int32)

In [165]:
ar3[:,1:2]

array([[12],
       [30],
       [48],
       [66],
       [84]], dtype=int32)

In [166]:
ar3[2:4,6:8]

array([[58, 60],
       [76, 78]], dtype=int32)

In [167]:
np.nditer(ar3)

In [168]:
for i in ar3:
    print(i)

[ 10  12 100  16  18  20  22  24  26]
[28 30 32 34 36 38 40 42 44]
[46 48 50 52 54 56 58 60 62]
[64 66 68 70 72 74 76 78 80]
[82 84 86 88 90 92 94 96 98]


In [169]:
for i in np.nditer(ar3):
    print(i)

10
12
100
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98


In [170]:
ar3.flat

In [171]:
for i in ar3.flat:
    print(i)

10
12
100
16
18
20
22
24
26
28
30
32
34
36
38
40
42
44
46
48
50
52
54
56
58
60
62
64
66
68
70
72
74
76
78
80
82
84
86
88
90
92
94
96
98


In [172]:
np.nditer(ar3)

In [173]:
np.where(ar3>3)

(array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4,
        4]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3,
        4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7, 8, 0, 1, 2, 3, 4, 5, 6, 7,
        8]))

In [174]:
ar3>55

array([[False, False,  True, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [175]:
np.sqrt(ar3)

array([[ 3.16227766,  3.46410162, 10.        ,  4.        ,  4.24264069,
         4.47213595,  4.69041576,  4.89897949,  5.09901951],
       [ 5.29150262,  5.47722558,  5.65685425,  5.83095189,  6.        ,
         6.164414  ,  6.32455532,  6.4807407 ,  6.63324958],
       [ 6.78232998,  6.92820323,  7.07106781,  7.21110255,  7.34846923,
         7.48331477,  7.61577311,  7.74596669,  7.87400787],
       [ 8.        ,  8.1240384 ,  8.24621125,  8.36660027,  8.48528137,
         8.60232527,  8.71779789,  8.83176087,  8.94427191],
       [ 9.05538514,  9.16515139,  9.2736185 ,  9.38083152,  9.48683298,
         9.59166305,  9.69535971,  9.79795897,  9.89949494]])

In [176]:
np.median(ar3)

np.float64(56.0)

In [177]:
np.sin(ar3)

array([[-0.54402111, -0.53657292, -0.50636564, -0.28790332, -0.75098725,
         0.91294525, -0.00885131, -0.90557836,  0.76255845],
       [ 0.27090579, -0.98803162,  0.55142668,  0.52908269, -0.99177885,
         0.29636858,  0.74511316, -0.91652155,  0.01770193],
       [ 0.90178835, -0.76825466, -0.26237485,  0.98662759, -0.55878905,
        -0.521551  ,  0.99287265, -0.30481062, -0.7391807 ],
       [ 0.92002604, -0.02655115, -0.89792768,  0.77389068,  0.25382336,
        -0.98514626,  0.56610764,  0.51397846, -0.99388865],
       [ 0.31322878,  0.73319032, -0.92345845,  0.0353983 ,  0.89399666,
        -0.77946607, -0.24525199,  0.98358775, -0.57338187]])

In [178]:
np.mean(ar3)

np.float64(55.91111111111111)

In [179]:
ar3.mean

<function ndarray.mean>

In [180]:
ar3.mean()

np.float64(55.91111111111111)

In [181]:
ar3.std()

np.float64(26.124337075882348)

In [182]:
ar3.transpose()

array([[ 10,  28,  46,  64,  82],
       [ 12,  30,  48,  66,  84],
       [100,  32,  50,  68,  86],
       [ 16,  34,  52,  70,  88],
       [ 18,  36,  54,  72,  90],
       [ 20,  38,  56,  74,  92],
       [ 22,  40,  58,  76,  94],
       [ 24,  42,  60,  78,  96],
       [ 26,  44,  62,  80,  98]], dtype=int32)

In [183]:
np.transpose(ar3)

array([[ 10,  28,  46,  64,  82],
       [ 12,  30,  48,  66,  84],
       [100,  32,  50,  68,  86],
       [ 16,  34,  52,  70,  88],
       [ 18,  36,  54,  72,  90],
       [ 20,  38,  56,  74,  92],
       [ 22,  40,  58,  76,  94],
       [ 24,  42,  60,  78,  96],
       [ 26,  44,  62,  80,  98]], dtype=int32)

In [184]:
ar3.T

array([[ 10,  28,  46,  64,  82],
       [ 12,  30,  48,  66,  84],
       [100,  32,  50,  68,  86],
       [ 16,  34,  52,  70,  88],
       [ 18,  36,  54,  72,  90],
       [ 20,  38,  56,  74,  92],
       [ 22,  40,  58,  76,  94],
       [ 24,  42,  60,  78,  96],
       [ 26,  44,  62,  80,  98]], dtype=int32)

In [185]:
ar3

array([[ 10,  12, 100,  16,  18,  20,  22,  24,  26],
       [ 28,  30,  32,  34,  36,  38,  40,  42,  44],
       [ 46,  48,  50,  52,  54,  56,  58,  60,  62],
       [ 64,  66,  68,  70,  72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90,  92,  94,  96,  98]], dtype=int32)

In [186]:
ar3.transpose()

array([[ 10,  28,  46,  64,  82],
       [ 12,  30,  48,  66,  84],
       [100,  32,  50,  68,  86],
       [ 16,  34,  52,  70,  88],
       [ 18,  36,  54,  72,  90],
       [ 20,  38,  56,  74,  92],
       [ 22,  40,  58,  76,  94],
       [ 24,  42,  60,  78,  96],
       [ 26,  44,  62,  80,  98]], dtype=int32)

In [187]:
ar3

array([[ 10,  12, 100,  16,  18,  20,  22,  24,  26],
       [ 28,  30,  32,  34,  36,  38,  40,  42,  44],
       [ 46,  48,  50,  52,  54,  56,  58,  60,  62],
       [ 64,  66,  68,  70,  72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90,  92,  94,  96,  98]], dtype=int32)

In [188]:
ar3

array([[ 10,  12, 100,  16,  18,  20,  22,  24,  26],
       [ 28,  30,  32,  34,  36,  38,  40,  42,  44],
       [ 46,  48,  50,  52,  54,  56,  58,  60,  62],
       [ 64,  66,  68,  70,  72,  74,  76,  78,  80],
       [ 82,  84,  86,  88,  90,  92,  94,  96,  98]], dtype=int32)

In [189]:
ar2

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [190]:
kmv_arr

array([[21, 22, 23],
       [44, 55, 66]])

In [191]:
jarr =np.array([
    [37,32,77],
    [88,33,45],
    [89,99,34],
[98,90,32]])

In [192]:
jarr

array([[37, 32, 77],
       [88, 33, 45],
       [89, 99, 34],
       [98, 90, 32]])

In [193]:
karr= np.arange(12).reshape(4,3)
karr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [194]:
np.hstack((karr,jarr))

array([[ 0,  1,  2, 37, 32, 77],
       [ 3,  4,  5, 88, 33, 45],
       [ 6,  7,  8, 89, 99, 34],
       [ 9, 10, 11, 98, 90, 32]])

In [195]:
np.vstack((jarr,karr))

array([[37, 32, 77],
       [88, 33, 45],
       [89, 99, 34],
       [98, 90, 32],
       [ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [196]:
np.hsplit(jarr,3)

[array([[37],
        [88],
        [89],
        [98]]),
 array([[32],
        [33],
        [99],
        [90]]),
 array([[77],
        [45],
        [34],
        [32]])]

In [197]:
np.vsplit(jarr,2)

[array([[37, 32, 77],
        [88, 33, 45]]),
 array([[89, 99, 34],
        [98, 90, 32]])]

In [198]:
jarr

array([[37, 32, 77],
       [88, 33, 45],
       [89, 99, 34],
       [98, 90, 32]])

In [199]:
jarr[1,2]

np.int64(45)

In [200]:
jarr[1:3,1:]

array([[33, 45],
       [99, 34]])

In [201]:
jarr[[0,3]]

array([[37, 32, 77],
       [98, 90, 32]])

In [202]:
jarr[[0,2],2:]

array([[77],
       [34]])

In [203]:
jarr[jarr<40]

array([37, 32, 33, 34, 32])

In [204]:
jarr[(jarr<40) & (jarr>35)]

array([37])

In [205]:
arr11 = np.array([
    [23,22,55],
    [12,76,33]])
arr22 = np.arange(3)

In [206]:
arr11

array([[23, 22, 55],
       [12, 76, 33]])

In [207]:
arr22

array([0, 1, 2])

In [208]:
arr22+arr11

array([[23, 23, 57],
       [12, 77, 35]])

In [209]:
np.array([[1],[2]])

array([[1],
       [2]])

In [210]:
arr11

array([[23, 22, 55],
       [12, 76, 33]])

In [211]:
arr11+np.array([[1],[2]])

array([[24, 23, 56],
       [14, 78, 35]])

In [212]:
np.random.random([2,8,2,2])  #creating n dimensinal random numbers array

array([[[[0.3545083 , 0.64276099],
         [0.44950171, 0.54882657]],

        [[0.60777621, 0.00664132],
         [0.66390082, 0.17685688]],

        [[0.91967116, 0.73316053],
         [0.7498419 , 0.29802152]],

        [[0.31649427, 0.27457339],
         [0.60023853, 0.83615246]],

        [[0.70204891, 0.66723177],
         [0.16331595, 0.53731103]],

        [[0.91837182, 0.03578954],
         [0.86078481, 0.56195472]],

        [[0.10942895, 0.97853039],
         [0.30846645, 0.72769107]],

        [[0.45252104, 0.22306372],
         [0.35566976, 0.13504214]]],


       [[[0.14228291, 0.42272776],
         [0.04853556, 0.87372098]],

        [[0.45075348, 0.48020271],
         [0.08183095, 0.97210193]],

        [[0.10198765, 0.17044604],
         [0.34080875, 0.78195199]],

        [[0.24879162, 0.06649052],
         [0.39592499, 0.90472389]],

        [[0.31843326, 0.68068786],
         [0.32343778, 0.56485939]],

        [[0.24830344, 0.7818702 ],
         [0.65954821, 0.584

In [213]:
np.random.random()

0.7816759427250168

In [214]:
np.random.rand()

0.002620149578537956

In [215]:
np.random.choice([5,2,99],p=[0.9,0.1,0],size=(5,10))

array([[5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 2, 5, 5],
       [5, 5, 5, 5, 5, 5, 5, 5, 5, 2]])

In [216]:
np.random.randint(4,size= (10,3))

array([[0, 0, 2],
       [3, 0, 1],
       [0, 2, 2],
       [3, 0, 0],
       [3, 0, 0],
       [2, 2, 3],
       [3, 3, 2],
       [0, 2, 2],
       [2, 2, 0],
       [1, 1, 0]], dtype=int32)

In [217]:
np.random.randint(low= 5,high = 15,size = 8)

array([12,  7,  8, 14,  8,  7, 10, 12], dtype=int32)

In [218]:
kmv_arr

array([[21, 22, 23],
       [44, 55, 66]])

In [219]:
kmv_arr.ravel()

array([21, 22, 23, 44, 55, 66])

In [220]:
np.percentile(kmv_arr.ravel(),99)

np.float64(65.45)

In [221]:
np.random.seed(2)
print(np.random.random())
np.random.random()

0.43599490214200376


0.025926231827891333

In [222]:
np.random.seed(2)
np.random.random()

0.43599490214200376

In [223]:
np.random.rand(2,3,4)

array([[[0.02592623, 0.54966248, 0.43532239, 0.4203678 ],
        [0.33033482, 0.20464863, 0.61927097, 0.29965467],
        [0.26682728, 0.62113383, 0.52914209, 0.13457995]],

       [[0.51357812, 0.18443987, 0.78533515, 0.85397529],
        [0.49423684, 0.84656149, 0.07964548, 0.50524609],
        [0.0652865 , 0.42812233, 0.09653092, 0.12715997]]])

In [231]:
np.random.rand(2,3,2)

array([[[0.06571068, 0.31728336],
        [0.58555545, 0.52413135],
        [0.43512262, 0.91267715]],

       [[0.56997665, 0.93413675],
        [0.57615435, 0.18518019],
        [0.98207871, 0.99850326]]])

In [232]:
np.random.random([2,3,2])

array([[[0.44646811, 0.76243056],
        [0.63656342, 0.18524397],
        [0.57920196, 0.65424193]],

       [[0.59374037, 0.54147664],
        [0.59187907, 0.70899117],
        [0.77097797, 0.0890502 ]]])

In [233]:
np.random.random((2,3,2))

array([[[0.91349549, 0.44962501],
        [0.69662112, 0.38763905],
        [0.05105715, 0.66364126]],

       [[0.36566056, 0.55277996],
        [0.26658984, 0.20387608],
        [0.29620495, 0.84186763]]])

In [235]:
np.random.randint(3)

2

In [238]:
np.random.randint(2,29)

6

In [241]:
np.random.randint(2,23,8)

array([12,  8, 13, 12, 14,  4, 18,  7], dtype=int32)

In [243]:
np.random.randint(2,32,(3,4,2))

array([[[14, 18],
        [30, 30],
        [29, 16],
        [13, 21]],

       [[10, 16],
        [26,  4],
        [31, 15],
        [31, 16]],

       [[30, 28],
        [14, 10],
        [25, 31],
        [12, 11]]], dtype=int32)

In [245]:
np.random.randint(low = 3,high = 44,size = (2,3),dtype = np.int8)

array([[35, 28, 41],
       [34, 13, 32]], dtype=int8)

In [249]:
np.random.randint(low = 10) # if high not provided then generate random numbers b/w 0 and low

6

In [251]:
np.random.randint(2,high = 3)

2

In [258]:
np.random.choice((2,3,4),(2,4),p = [1,0,0])

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

In [261]:
np.random.choice(a= [2,3,8],size = [2,3,4],replace = True,p = [0.2,0.7,0.1])

array([[[3, 3, 3, 3],
        [2, 2, 3, 3],
        [2, 3, 3, 2]],

       [[3, 3, 2, 3],
        [8, 8, 3, 3],
        [3, 3, 3, 3]]])

In [270]:
np.random.choice(a = [2,4,8,3,9],size = [1,3],replace = False,p = [0.2,0.3,0.1,0.2,0.2]) # replace = True is default value and it genereated repated values

array([[9, 3, 2]])

In [282]:
np.random.choice([2,4,6,2],[2,2],[0.1,0.2,0.4,0.3])

array([[4, 2],
       [6, 4]])

In [280]:
np.random.choice([2,3,6,5],[2,2],False,[0.2,0.1,0.4,0.3])

array([[3, 6],
       [5, 2]])